version: "3.3"
services:    
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    restart: always
    ports:
      - 8080:80
    
  wordpress:
    image: conetix/wordpress-with-wp-cli
    container_name: wordpress
    ports:
      - 80:80
    restart: always
    environment:
      WORDPRESS_DB_HOST: ${DockerWordpressMaster.Endpoint.Address}:3306
      WORDPRESS_DB_NAME: wordpressdb
      WORDPRESS_DB_USER: DocWorUser
      WORDPRESS_DB_PASSWORD: DocWorPwd
      WORDPRESS_TABLE_PREFIX: "wp_"
      WORDPRESS_DEBUG: 1
    volumes:
      - wp_data:/var/www/html
volumes:
  wp_data:
